import os


ARCADE_BASE_ENDPOINT = os.getenv("ARCADE_API_ENDPOINT", "/api/v1")
ARCADE_BASE_SERVER_ENDPOINT = f"{ARCADE_BASE_ENDPOINT}/server"
ARCADE_BASE_EXISTS_ENDPOINT = f"{ARCADE_BASE_ENDPOINT}/exists"
ARCADE_BASE_COMMAND_ENDPOINT = f"{ARCADE_BASE_ENDPOINT}/command"

API_RETRY_MAX = int(os.getenv("ARCADE_API_RETRY_MAX", 3))
API_RETRY_DELAY = int(os.getenv("ARCADE_API_RETRY_DELAY", 1))
API_RETRY_BACKOFF = int(os.getenv("ARCADE_API_RETRY_BACKOFF", 2))
